### ISSUE TITLE
ALSA keeping pulseaudio up at night

### ISSUE THREAD

**Issue by mutte-79** [alsa-project/alsa-firmware#5]
Hi there. I just got a message from pulseaudio[1137], asking me to tell relay the message so here I am.

**pulseaudio[1137]** ALSA woke us up to write new data to the device, but there was actually nothing to write.
**pulseaudio[1137]** Most likely this is a bug in the ALSA driver 'snd_usb_audio'. Please report this issue to the ALSA developers.
**pulseaudio[1137]**We were woken up with POLLOUT set -- however a subsequent snd_pcm_avail() returned 0 or another value < min_avail.

a couple of minutes later Sir systemd[1] shed some further light on the situation.

**systemd[1]**[origin software="rsyslogd" swVersion="8.2006.0" x-pid="868" x-info="https://www.rsyslog.com"] rsyslogd was HUPed

I have saved the log in case you need more info.

Med vänliga hälsninger
With kind regards

Mattias Högfjäll

**Comment by mutte-79** [comment]
Hi again. I found another polite request in my logs today.

ALSA woke us up to write new data to the device, but there was actually nothing to write.
Most likely this is a bug in the ALSA driver 'snd_usb_audio'. Please report this issue to the ALSA developers.
We were woken up with POLLOUT set -- however a subsequent snd_pcm_avail() returned 0 or another value < min_avail.

**Comment by mutte-79** [comment]
Oh, that is the exact same thing isn't it. I'm sorry I should have read it more thorough.

**Comment by perexg** [comment]
Dup of https://github.com/alsa-project/alsa-lib/issues/90 .
