### ISSUE TITLE
likely  this is a bug in the ALSA driver 'snd_soc_sst_cht_bsw_rt5645'

### ISSUE THREAD

**Issue by mcman56** [alsa-project/alsa-firmware#8]
pulseaudio	Most likely this is a bug in the ALSA driver 'snd_soc_sst_cht_bsw_rt5645'. Please report this issue to the ALSA developers.

I'm running Lubuntu 22.04 on a Chromebook 3.  The system will lock up when playing video or just sound.  This happens on multiple Linux versions and multiple browsers.  Sometimes closing the browser with Ctrl+q  recovers.  Sometimes a reboot is required to get a functional wifi connection.  The attached log is form a failure when running just sound on Pithos.   This required a reboot.     

Samsung Chromebook 3 (Intel Celeron N3050, Braswell dual core @ 1.6GHz, Memory: 2GB,  Network controller [0280]: Intel Corporation Wireless 7265 [8086:095a] (rev 59) 7265D

[print.pdf](https://github.com/alsa-project/alsa-firmware/files/10354475/print.pdf)

**Comment by perexg** [comment]
It seems that the wireless (WiFi) driver has some issues for your hardware and it may block the audio driver. Report this to iwlwifi maintainers:

```
INTEL WIRELESS WIFI LINK (iwlwifi)
M:      Gregory Greenman <gregory.greenman@intel.com>
L:      linux-wireless@vger.kernel.org
S:      Supported
W:      https://wireless.wiki.kernel.org/en/users/drivers/iwlwifi
T:      git git://git.kernel.org/pub/scm/linux/kernel/git/iwlwifi/iwlwifi.git
F:      drivers/net/wireless/intel/iwlwifi/
```
